name: Daily Commit Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Use the PAT here

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "25ds1000038@ds.study.iitm.ac.in"

      - name: Make a Dummy Commit
        run: |
          git commit --allow-empty -m "Automated daily commit - $(date)" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin main || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use the PAT here
