name: 25ds1000038@ds.study.iitm.ac.in

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Use the PAT instead of GITHUB_TOKEN

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "25ds1000038@ds.study.iitm.ac.in"
          git config --global credential.helper store

      - name: Authenticate with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/PG-13v1/ga4.git

      - name: Make an Empty Commit
        run: |
          git commit --allow-empty -m "Automated daily commit - $(date)" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin main || echo "No changes to push"

